products = {
  "Apple" => { price: 5, category: "Fruit", import_duty: false },
  "Wine" => { price: 100, category: "Liquor", import_duty: false },
  "Banana" => { price: 5, category: "Fruit", import_duty: false },
  "Orange" => { price: 6, category: "Fruit", import_duty: false },
  "Broccoli" => { price: 8, category: "Vegetable", import_duty: false },
  "Dark Leafy Greens" => { price: 7, category: "Vegetable", import_duty: false },
  "Tomatoes" => { price: 4, category: "Vegetable", import_duty: false },
  "Avocados" => { price: 10, category: "Fruit", import_duty: false },
  "Blueberries" => { price: 12, category: "Fruit", import_duty: false },
  "Raspberries" => { price: 15, category: "Fruit", import_duty: false },
  "Milk" => { price: 3, category: "Dairy", import_duty: false },
  "Cream" => { price: 4, category: "Dairy", import_duty: false },
  "Butter" => { price: 5, category: "Dairy", import_duty: false },
  "Fermented Yogurt" => { price: 6, category: "Dairy", import_duty: false },
  "Cheese" => { price: 8, category: "Dairy", import_duty: false },
  "Custard" => { price: 7, category: "Dairy", import_duty: false },
  "Frozen" => { price: 9, category: "Dairy", import_duty: false }
}
